service: betting-roulette
package:
  individually: true
provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1
  architecture: arm64
  stage: ${env:STAGE}
  timeout: 60
  environment:
    ROULETTE_TABLE: roulette-${self:provider.stage}
    BET_TABLE: bet-${self:provider.stage}
  tracing:
    apiGateway: true
    lambda: true
  iam:
    role:
      statements:
        - Effect: 'Allow'
          Action:
            - xray:PutTelemetryRecords
            - xray:PutTraceSegments
          Resource: '*'
custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
    packager: 'npm'
    excludeFiles: src/**/*.test.[t|j]s
  dynamodb:
    start:
      port: 8000
      inMemory: true
      migrate: true
      seed: true
      convertEmptyValues: true
    stages:
      - dev
      - local
  warmup:
    enabled: true
    events:
      - schedule: rate(5 minutes)
    prewarm: true
    concurrency: 1
  prune:
    automatic: true
    number: 5
  serverless-offline:
    httpPort: 4000
functions: ${file(./yml/functions.yml)}
resources:
  - ${file(./yml/resources/dynamodb.yml)}
plugins:
  - serverless-dynamodb-local
  - serverless-webpack
  - serverless-offline
  - serverless-plugin-warmup
  - serverless-dotenv-plugin
  - serverless-iam-roles-per-function
